# Base URL
base.url=https://www.automationexercise.com
login.url=https://www.automationexercise.com/login
signup.url=https://www.automationexercise.com/signup
products.url=https://automationexercise.com/products
cart.url=https://automationexercise.com/view_cart

# Browser
browser=chrome
headless=false

# Timeouts (seconds)
timeout.default=10
timeout.page.load=30