# Base URL
base.url=https://www.automationexercise.com
login.url=https://www.automationexercise.com/login
signup.url=https://www.automationexercise.com/signup
products.url=https://automationexercise.com/products
product.detail.url=https://automationexercise.com/product_details/
cart.url=https://automationexercise.com/view_cart
test.cases.url=https://automationexercise.com/test_cases

# Browser
browser=chrome
headless=false

# Timeouts (seconds)
timeout.default=10
timeout.page.load=30

# Random email address
random.email=random@mail.com